export const BURGER_TOGGLE_IS_MENU_ACTIVE = 'BURGER_TOGGLE_IS_MENU_ACTIVE';
export const BURGER_TOGGLE_SOUND = 'BURGER_TOGGLE_SOUND';
export const BURGER_TOGGLE_MUSIC = 'BURGER_TOGGLE_MUSIC';
export const BURGER_SET_SOUND_VOLUME = 'BURGER_SET_SOUND_VOLUME';
export const BURGER_SET_CARDS_BG = 'BURGER_SET_CARDS_BG';
export const BURGER_SET_OPACITY_BG = 'BURGER_SET_OPACITY_BG';